services:
  proxy:
    image: nginxproxy/nginx-proxy:1.11.6
    container_name: "${PROXY}"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.nginx-proxy.nginx: ""
    environment:
      TRUST_DOWNSTREAM_PROXY: "false"
    volumes:
      - "${CONTAINER_SOCKET:-/var/run/docker.sock}:/tmp/docker.sock:ro"
      - "proxy-certs:/etc/nginx/certs:ro"
      - "proxy-html:/usr/share/nginx/html:ro"
      - "proxy-htpasswd:/etc/nginx/htpasswd:ro"
      - "proxy-vhost:/etc/nginx/vhost.d:ro"
      - "./etc/nginx/proxy.conf:/etc/nginx/conf.d/zz-home-server.conf:ro"
    networks:
      - proxy-tier
  proxy-letsencrypt:
    image: nginxproxy/acme-companion:2.8.2
    container_name: "${LETS_ENCRYPT}"
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - "${CONTAINER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "proxy-certs:/etc/nginx/certs:rw"
      - "proxy-html:/usr/share/nginx/html:rw"
      - "proxy-acme:/etc/acme.sh"
    environment:
      DEFAULT_EMAIL: "${ACME_EMAIL}"
      CREATE_DEFAULT_CERTIFICATE: "true"
    networks:
      - proxy-tier

volumes:
  proxy-certs:
  proxy-html:
  proxy-htpasswd:
  proxy-vhost:
  proxy-acme:
networks:
  proxy-tier:
    name: proxy-tier
    driver: bridge
