version: '3.9'
services:
  proxy:
    build:
      context: .
      dockerfile: proxy.dockerfile
    container_name: '${PROXY}'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - 'proxy-certs:/etc/nginx/certs:rw'
      - 'proxy-conf:/etc/nginx/conf.d'
      - 'proxy-html:/usr/share/nginx/html'
      - 'proxy-htpasswd:/etc/nginx/htpasswd:ro'
      - 'proxy-vhost:/etc/nginx/vhost.d'
    networks:
      - proxy-tier
  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: '${LETS_ENCRYPT}'
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'proxy-certs:/etc/nginx/certs:rw'
      - 'proxy-conf:/etc/nginx/conf.d'
      - 'proxy-html:/usr/share/nginx/html'
      - 'proxy-htpasswd:/etc/nginx/htpasswd:ro'
      - 'proxy-vhost:/etc/nginx/vhost.d'
    environment:
      NGINX_PROXY_CONTAINER: '${PROXY}'
  db:
    image: mysql:8.0.23
    container_name: db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
    volumes:
      - db-volume:/var/lib/mysql
      - './etc/mysql/conf.d:/etc/mysql/conf.d'
    cap_add:
      - SYS_NICE # Silence mbind errors: mbind: Operation not permitted
    networks:
      - proxy-tier
  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - proxy-tier

volumes:
  db-volume:
  proxy-certs:
  proxy-conf:
  proxy-html:
  proxy-htpasswd:
  proxy-vhost:
networks:
  proxy-tier:
    driver: bridge
