server_tokens off;
client_max_body_size 10g;
proxy_send_timeout 300s;
proxy_read_timeout 300s;
send_timeout 300s;

limit_req_zone $binary_remote_addr zone=per_ip_requests:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=per_ip_connections:10m;
limit_req_status 429;
limit_req_log_level warn;
limit_req zone=per_ip_requests burst=30 nodelay;
limit_conn per_ip_connections 30;
